
import Header from "../components/Header";
import CreateEventDrawer from '../components/createEventDrawer';


import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata = {
  title: "Scheduler",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
       <Header />
        <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
        {children}
        </main>
        
        <CreateEventDrawer />
      </body>
    </html>
    </ClerkProvider>
  );
};
